development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "development_secret_key_base_change_in_production" } %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "test_secret_key_base" } %>

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>

